# Project: matematica
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o matematica.o
LINKOBJ  = main.o matematica.o
LIBS     = -L"C:/development/ide/dev-cpp/MinGW64/lib" -L"C:/development/ide/dev-cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/development/ide/dev-cpp/MinGW64/include" -I"C:/development/ide/dev-cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/development/ide/dev-cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"C:/development/ide/dev-cpp/MinGW64/include" -I"C:/development/ide/dev-cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/development/ide/dev-cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/development/ide/dev-cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = matematica.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

matematica.o: matematica.cpp
	$(CPP) -c matematica.cpp -o matematica.o $(CXXFLAGS)
